name = "tidbyt-mealviewer"
main = "worker.js"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

[browser]
binding = "BROWSER"

[triggers]
crons = ["0 * * * *"]

[vars]
TZ = "America/New_York"
